// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (file_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, file_id, user_id, content, created_at, updated_at, is_deleted
`

type CreateCommentParams struct {
	FileID  pgtype.UUID `json:"file_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.FileID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments
SET is_deleted = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, file_id, user_id, content, created_at, updated_at, is_deleted FROM comments
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getCommentsByUser = `-- name: GetCommentsByUser :many
SELECT
    c.id, c.file_id, c.user_id, c.content, c.created_at, c.updated_at, c.is_deleted,
    f.name as file_name
FROM comments c
JOIN files f ON c.file_id = f.id
WHERE c.user_id = $1
  AND c.is_deleted = FALSE
ORDER BY c.created_at DESC
LIMIT $2
`

type GetCommentsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetCommentsByUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	FileID    pgtype.UUID      `json:"file_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IsDeleted bool             `json:"is_deleted"`
	FileName  string           `json:"file_name"`
}

func (q *Queries) GetCommentsByUser(ctx context.Context, arg GetCommentsByUserParams) ([]GetCommentsByUserRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByUserRow{}
	for rows.Next() {
		var i GetCommentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileComments = `-- name: GetFileComments :many
SELECT
    c.id, c.file_id, c.user_id, c.content, c.created_at, c.updated_at, c.is_deleted,
    u.name as user_name,
    u.email
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.file_id = $1
  AND c.is_deleted = FALSE
ORDER BY c.created_at ASC
`

type GetFileCommentsRow struct {
	ID        pgtype.UUID      `json:"id"`
	FileID    pgtype.UUID      `json:"file_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IsDeleted bool             `json:"is_deleted"`
	UserName  string           `json:"user_name"`
	Email     string           `json:"email"`
}

func (q *Queries) GetFileComments(ctx context.Context, fileID pgtype.UUID) ([]GetFileCommentsRow, error) {
	rows, err := q.db.Query(ctx, getFileComments, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFileCommentsRow{}
	for rows.Next() {
		var i GetFileCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.UserName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, file_id, user_id, content, created_at, updated_at, is_deleted
`

type UpdateCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
