// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType string

const (
	ActivityTypeUpload   ActivityType = "upload"
	ActivityTypeDelete   ActivityType = "delete"
	ActivityTypeRestore  ActivityType = "restore"
	ActivityTypeShare    ActivityType = "share"
	ActivityTypeUnshare  ActivityType = "unshare"
	ActivityTypeRename   ActivityType = "rename"
	ActivityTypeMove     ActivityType = "move"
	ActivityTypeComment  ActivityType = "comment"
	ActivityTypeDownload ActivityType = "download"
	ActivityTypeStar     ActivityType = "star"
	ActivityTypeUnstar   ActivityType = "unstar"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activity_type"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type FileStatus string

const (
	FileStatusActive  FileStatus = "active"
	FileStatusTrashed FileStatus = "trashed"
	FileStatusDeleted FileStatus = "deleted"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type ItemType string

const (
	ItemTypeFile   ItemType = "file"
	ItemTypeFolder ItemType = "folder"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType `json:"item_type"`
	Valid    bool     `json:"valid"` // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type PermissionRole string

const (
	PermissionRoleViewer    PermissionRole = "viewer"
	PermissionRoleCommenter PermissionRole = "commenter"
	PermissionRoleEditor    PermissionRole = "editor"
	PermissionRoleOwner     PermissionRole = "owner"
)

func (e *PermissionRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionRole(s)
	case string:
		*e = PermissionRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionRole: %T", src)
	}
	return nil
}

type NullPermissionRole struct {
	PermissionRole PermissionRole `json:"permission_role"`
	Valid          bool           `json:"valid"` // Valid is true if PermissionRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionRole) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionRole), nil
}

type ActivityLog struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	FileID       pgtype.UUID      `json:"file_id"`
	ActivityType ActivityType     `json:"activity_type"`
	Details      []byte           `json:"details"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Comment struct {
	ID        pgtype.UUID      `json:"id"`
	FileID    pgtype.UUID      `json:"file_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IsDeleted bool             `json:"is_deleted"`
}

type File struct {
	ID               pgtype.UUID      `json:"id"`
	Name             string           `json:"name"`
	OriginalName     string           `json:"original_name"`
	MimeType         string           `json:"mime_type"`
	Size             int64            `json:"size"`
	StoragePath      string           `json:"storage_path"`
	OwnerID          pgtype.UUID      `json:"owner_id"`
	ParentFolderID   pgtype.UUID      `json:"parent_folder_id"`
	Status           NullFileStatus   `json:"status"`
	IsStarred        pgtype.Bool      `json:"is_starred"`
	ThumbnailPath    pgtype.Text      `json:"thumbnail_path"`
	PreviewAvailable pgtype.Bool      `json:"preview_available"`
	Version          pgtype.Int4      `json:"version"`
	CurrentVersionID pgtype.UUID      `json:"current_version_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	TrashedAt        pgtype.Timestamp `json:"trashed_at"`
	LastAccessedAt   pgtype.Timestamp `json:"last_accessed_at"`
}

type FileVersion struct {
	ID            pgtype.UUID      `json:"id"`
	FileID        pgtype.UUID      `json:"file_id"`
	VersionNumber int32            `json:"version_number"`
	StoragePath   string           `json:"storage_path"`
	Size          int64            `json:"size"`
	UploadedBy    pgtype.UUID      `json:"uploaded_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Folder struct {
	ID             pgtype.UUID      `json:"id"`
	Name           string           `json:"name"`
	OwnerID        pgtype.UUID      `json:"owner_id"`
	ParentFolderID pgtype.UUID      `json:"parent_folder_id"`
	IsRoot         pgtype.Bool      `json:"is_root"`
	Status         NullFileStatus   `json:"status"`
	IsStarred      pgtype.Bool      `json:"is_starred"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	TrashedAt      pgtype.Timestamp `json:"trashed_at"`
}

type Permission struct {
	ID        pgtype.UUID      `json:"id"`
	ItemType  ItemType         `json:"item_type"`
	ItemID    pgtype.UUID      `json:"item_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Role      PermissionRole   `json:"role"`
	GrantedBy pgtype.UUID      `json:"granted_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Share struct {
	ID         pgtype.UUID        `json:"id"`
	ItemType   ItemType           `json:"item_type"`
	ItemID     pgtype.UUID        `json:"item_id"`
	Token      string             `json:"token"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	Permission NullPermissionRole `json:"permission"`
	ExpiresAt  pgtype.Timestamp   `json:"expires_at"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamp   `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID      `json:"id"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	Name           string           `json:"name"`
	StorageUsed    pgtype.Int8      `json:"storage_used"`
	StorageLimit   pgtype.Int8      `json:"storage_limit"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
