// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateShare(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	GetFileActivity(ctx context.Context, arg GetFileActivityParams) ([]GetFileActivityRow, error)
	GetFileByID(ctx context.Context, id pgtype.UUID) (File, error)
	GetFilesByFolder(ctx context.Context, arg GetFilesByFolderParams) ([]File, error)
	GetFilesByOwner(ctx context.Context, arg GetFilesByOwnerParams) ([]File, error)
	GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetFoldersByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Folder, error)
	GetItemPermissions(ctx context.Context, arg GetItemPermissionsParams) ([]GetItemPermissionsRow, error)
	GetRecentFiles(ctx context.Context, arg GetRecentFilesParams) ([]File, error)
	GetRootFiles(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
	GetRootFolder(ctx context.Context, ownerID pgtype.UUID) (Folder, error)
	GetRootFolders(ctx context.Context, ownerID pgtype.UUID) ([]Folder, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetShareByToken(ctx context.Context, token string) (Share, error)
	GetSharedWithMeFiles(ctx context.Context, userID pgtype.UUID) ([]GetSharedWithMeFilesRow, error)
	GetSharedWithMeFolders(ctx context.Context, userID pgtype.UUID) ([]GetSharedWithMeFoldersRow, error)
	GetSharesByItem(ctx context.Context, arg GetSharesByItemParams) ([]Share, error)
	GetStarredFiles(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
	GetStorageUsage(ctx context.Context, id pgtype.UUID) (GetStorageUsageRow, error)
	GetSubfolders(ctx context.Context, parentFolderID pgtype.UUID) ([]Folder, error)
	GetTrashedFiles(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
	GetUserActivity(ctx context.Context, arg GetUserActivityParams) ([]GetUserActivityRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserPermissionForItem(ctx context.Context, arg GetUserPermissionForItemParams) (Permission, error)
	LogActivity(ctx context.Context, arg LogActivityParams) error
	MoveFile(ctx context.Context, arg MoveFileParams) error
	MoveFolder(ctx context.Context, arg MoveFolderParams) error
	PermanentDeleteFile(ctx context.Context, id pgtype.UUID) error
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) error
	RestoreFile(ctx context.Context, id pgtype.UUID) error
	RestoreFolder(ctx context.Context, id pgtype.UUID) error
	RevokePermission(ctx context.Context, arg RevokePermissionParams) error
	SearchFilesByName(ctx context.Context, arg SearchFilesByNameParams) ([]File, error)
	SearchFilesByType(ctx context.Context, arg SearchFilesByTypeParams) ([]File, error)
	SearchUsersByEmail(ctx context.Context, dollar_1 pgtype.Text) ([]SearchUsersByEmailRow, error)
	ToggleStarFile(ctx context.Context, id pgtype.UUID) error
	TrashFile(ctx context.Context, id pgtype.UUID) error
	TrashFolder(ctx context.Context, id pgtype.UUID) error
	UpdateLastAccessed(ctx context.Context, id pgtype.UUID) error
	UpdateUserStorage(ctx context.Context, arg UpdateUserStorageParams) error
}

var _ Querier = (*Queries)(nil)
