// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFilePermission(ctx context.Context, arg CreateFilePermissionParams) (FilePermission, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateShareLink(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	GetFileActivity(ctx context.Context, arg GetFileActivityParams) ([]GetFileActivityRow, error)
	GetFileByID(ctx context.Context, id pgtype.UUID) (File, error)
	GetFilePermissions(ctx context.Context, fileID pgtype.UUID) ([]GetFilePermissionsRow, error)
	GetFilesByFolder(ctx context.Context, parentFolderID pgtype.UUID) ([]File, error)
	GetFilesByOwner(ctx context.Context, arg GetFilesByOwnerParams) ([]File, error)
	GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetFoldersByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Folder, error)
	GetRecentFiles(ctx context.Context, arg GetRecentFilesParams) ([]File, error)
	GetRootFolder(ctx context.Context, ownerID pgtype.UUID) (Folder, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error)
	GetShareLinksByFile(ctx context.Context, fileID pgtype.UUID) ([]ShareLink, error)
	GetSharedWithMeFiles(ctx context.Context, userID pgtype.UUID) ([]GetSharedWithMeFilesRow, error)
	GetStarredFiles(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
	GetStorageUsage(ctx context.Context, id pgtype.UUID) (GetStorageUsageRow, error)
	GetSubfolders(ctx context.Context, parentFolderID pgtype.UUID) ([]Folder, error)
	GetTrashedFiles(ctx context.Context, ownerID pgtype.UUID) ([]File, error)
	GetUserActivity(ctx context.Context, arg GetUserActivityParams) ([]GetUserActivityRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserPermissionForFile(ctx context.Context, arg GetUserPermissionForFileParams) (FilePermission, error)
	LogActivity(ctx context.Context, arg LogActivityParams) error
	MoveFile(ctx context.Context, arg MoveFileParams) error
	PermanentDeleteFile(ctx context.Context, id pgtype.UUID) error
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) error
	RestoreFile(ctx context.Context, id pgtype.UUID) error
	RestoreFolder(ctx context.Context, id pgtype.UUID) error
	RevokePermission(ctx context.Context, arg RevokePermissionParams) error
	SearchFilesByName(ctx context.Context, arg SearchFilesByNameParams) ([]File, error)
	SearchFilesByType(ctx context.Context, arg SearchFilesByTypeParams) ([]File, error)
	ToggleStarFile(ctx context.Context, id pgtype.UUID) error
	TrashFile(ctx context.Context, id pgtype.UUID) error
	TrashFolder(ctx context.Context, id pgtype.UUID) error
	UpdateLastAccessed(ctx context.Context, id pgtype.UUID) error
	UpdateUserStorage(ctx context.Context, arg UpdateUserStorageParams) error
}

var _ Querier = (*Queries)(nil)
