// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentStorageGrowth = `-- name: GetRecentStorageGrowth :many
SELECT
    DATE(created_at) as date,
    COUNT(*) as files_added,
    COALESCE(SUM(size), 0) as storage_added
FROM files
WHERE owner_id = $1
  AND created_at >= NOW() - INTERVAL '30 days'
  AND status = 'active'
GROUP BY DATE(created_at)
ORDER BY date DESC
`

type GetRecentStorageGrowthRow struct {
	Date         pgtype.Date `json:"date"`
	FilesAdded   int64       `json:"files_added"`
	StorageAdded interface{} `json:"storage_added"`
}

func (q *Queries) GetRecentStorageGrowth(ctx context.Context, ownerID pgtype.UUID) ([]GetRecentStorageGrowthRow, error) {
	rows, err := q.db.Query(ctx, getRecentStorageGrowth, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentStorageGrowthRow{}
	for rows.Next() {
		var i GetRecentStorageGrowthRow
		if err := rows.Scan(&i.Date, &i.FilesAdded, &i.StorageAdded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageByFileType = `-- name: GetStorageByFileType :many
SELECT
    CASE
        WHEN mime_type LIKE 'image/%' THEN 'Images'
        WHEN mime_type LIKE 'video/%' THEN 'Videos'
        WHEN mime_type LIKE 'audio/%' THEN 'Audio'
        WHEN mime_type = 'application/pdf' THEN 'PDFs'
        WHEN mime_type LIKE 'application/vnd.ms-%' OR
             mime_type LIKE 'application/vnd.openxmlformats-officedocument%' OR
             mime_type LIKE 'application/msword%' THEN 'Documents'
        WHEN mime_type LIKE 'application/zip%' OR
             mime_type LIKE 'application/x-rar%' OR
             mime_type LIKE 'application/x-7z%' THEN 'Archives'
        WHEN mime_type LIKE 'text/%' THEN 'Text Files'
        ELSE 'Other'
    END as file_type,
    COUNT(*) as file_count,
    COALESCE(SUM(size), 0) as total_size
FROM files
WHERE owner_id = $1 AND status = 'active'
GROUP BY file_type
ORDER BY total_size DESC
`

type GetStorageByFileTypeRow struct {
	FileType  string      `json:"file_type"`
	FileCount int64       `json:"file_count"`
	TotalSize interface{} `json:"total_size"`
}

func (q *Queries) GetStorageByFileType(ctx context.Context, ownerID pgtype.UUID) ([]GetStorageByFileTypeRow, error) {
	rows, err := q.db.Query(ctx, getStorageByFileType, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStorageByFileTypeRow{}
	for rows.Next() {
		var i GetStorageByFileTypeRow
		if err := rows.Scan(&i.FileType, &i.FileCount, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStorageStats = `-- name: GetUserStorageStats :one
SELECT
    u.storage_used,
    u.storage_limit,
    COUNT(DISTINCT f.id) as total_files,
    COUNT(DISTINCT fo.id) as total_folders
FROM users u
LEFT JOIN files f ON f.owner_id = u.id AND f.status = 'active'
LEFT JOIN folders fo ON fo.owner_id = u.id AND fo.status = 'active'
WHERE u.id = $1
GROUP BY u.id, u.storage_used, u.storage_limit
`

type GetUserStorageStatsRow struct {
	StorageUsed  pgtype.Int8 `json:"storage_used"`
	StorageLimit pgtype.Int8 `json:"storage_limit"`
	TotalFiles   int64       `json:"total_files"`
	TotalFolders int64       `json:"total_folders"`
}

func (q *Queries) GetUserStorageStats(ctx context.Context, id pgtype.UUID) (GetUserStorageStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStorageStats, id)
	var i GetUserStorageStatsRow
	err := row.Scan(
		&i.StorageUsed,
		&i.StorageLimit,
		&i.TotalFiles,
		&i.TotalFolders,
	)
	return i, err
}
