// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hashed_password, name)
VALUES ($1, $2, $3)
RETURNING id, email, hashed_password, name, storage_used, storage_limit, created_at, updated_at
`

type CreateUserParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	Name           string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.HashedPassword, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Name,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageUsage = `-- name: GetStorageUsage :one
SELECT storage_used, storage_limit FROM users WHERE id = $1
`

type GetStorageUsageRow struct {
	StorageUsed  pgtype.Int8 `json:"storage_used"`
	StorageLimit pgtype.Int8 `json:"storage_limit"`
}

func (q *Queries) GetStorageUsage(ctx context.Context, id pgtype.UUID) (GetStorageUsageRow, error) {
	row := q.db.QueryRow(ctx, getStorageUsage, id)
	var i GetStorageUsageRow
	err := row.Scan(&i.StorageUsed, &i.StorageLimit)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, name, storage_used, storage_limit, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Name,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, name, storage_used, storage_limit, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Name,
		&i.StorageUsed,
		&i.StorageLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, email, name, created_at FROM users
WHERE email ILIKE '%' || $1 || '%'
LIMIT 10
`

type SearchUsersByEmailRow struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) SearchUsersByEmail(ctx context.Context, dollar_1 pgtype.Text) ([]SearchUsersByEmailRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByEmail, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByEmailRow{}
	for rows.Next() {
		var i SearchUsersByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStorage = `-- name: UpdateUserStorage :exec
UPDATE users
SET storage_used = storage_used + $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStorageParams struct {
	ID          pgtype.UUID `json:"id"`
	StorageUsed pgtype.Int8 `json:"storage_used"`
}

func (q *Queries) UpdateUserStorage(ctx context.Context, arg UpdateUserStorageParams) error {
	_, err := q.db.Exec(ctx, updateUserStorage, arg.ID, arg.StorageUsed)
	return err
}
