// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileVersion = `-- name: CreateFileVersion :one
INSERT INTO file_versions (file_id, version_number, storage_path, size, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_id, version_number, storage_path, size, uploaded_by, created_at
`

type CreateFileVersionParams struct {
	FileID        pgtype.UUID `json:"file_id"`
	VersionNumber int32       `json:"version_number"`
	StoragePath   string      `json:"storage_path"`
	Size          int64       `json:"size"`
	UploadedBy    pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateFileVersion(ctx context.Context, arg CreateFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, createFileVersion,
		arg.FileID,
		arg.VersionNumber,
		arg.StoragePath,
		arg.Size,
		arg.UploadedBy,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.StoragePath,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileVersions = `-- name: DeleteFileVersions :exec
DELETE FROM file_versions
WHERE file_id = $1
`

func (q *Queries) DeleteFileVersions(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileVersions, fileID)
	return err
}

const getFileVersion = `-- name: GetFileVersion :one
SELECT fv.id, fv.file_id, fv.version_number, fv.storage_path, fv.size, fv.uploaded_by, fv.created_at, u.name as uploader_name
FROM file_versions fv
JOIN users u ON fv.uploaded_by = u.id
WHERE fv.id = $1
`

type GetFileVersionRow struct {
	ID            pgtype.UUID      `json:"id"`
	FileID        pgtype.UUID      `json:"file_id"`
	VersionNumber int32            `json:"version_number"`
	StoragePath   string           `json:"storage_path"`
	Size          int64            `json:"size"`
	UploadedBy    pgtype.UUID      `json:"uploaded_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UploaderName  string           `json:"uploader_name"`
}

func (q *Queries) GetFileVersion(ctx context.Context, id pgtype.UUID) (GetFileVersionRow, error) {
	row := q.db.QueryRow(ctx, getFileVersion, id)
	var i GetFileVersionRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VersionNumber,
		&i.StoragePath,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UploaderName,
	)
	return i, err
}

const getFileVersions = `-- name: GetFileVersions :many
SELECT fv.id, fv.file_id, fv.version_number, fv.storage_path, fv.size, fv.uploaded_by, fv.created_at, u.name as uploader_name, u.email as uploader_email
FROM file_versions fv
JOIN users u ON fv.uploaded_by = u.id
WHERE fv.file_id = $1
ORDER BY fv.version_number DESC
`

type GetFileVersionsRow struct {
	ID            pgtype.UUID      `json:"id"`
	FileID        pgtype.UUID      `json:"file_id"`
	VersionNumber int32            `json:"version_number"`
	StoragePath   string           `json:"storage_path"`
	Size          int64            `json:"size"`
	UploadedBy    pgtype.UUID      `json:"uploaded_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UploaderName  string           `json:"uploader_name"`
	UploaderEmail string           `json:"uploader_email"`
}

func (q *Queries) GetFileVersions(ctx context.Context, fileID pgtype.UUID) ([]GetFileVersionsRow, error) {
	rows, err := q.db.Query(ctx, getFileVersions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFileVersionsRow{}
	for rows.Next() {
		var i GetFileVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.VersionNumber,
			&i.StoragePath,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UploaderName,
			&i.UploaderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) as latest_version
FROM file_versions
WHERE file_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, fileID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestVersionNumber, fileID)
	var latest_version interface{}
	err := row.Scan(&latest_version)
	return latest_version, err
}
